steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=firebase-${_ENVIRONMENT}.enc
  - --plaintext-file=.${_ENVIRONMENT}.env
  - --location=global
  - --keyring=${_KEYRING_NAME}
  - --key=${_KEY_NAME}
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build:${_ENVIRONMENT}']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/firebase', '.' ]
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: ['functions:config:set', 'googlebooks.api_key="${_GOOGLE_BOOKS_API_KEY}"', '--project', '$PROJECT_ID']
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: ['--token', '${_FIREBASE_TOKEN}', 'deploy', '-P', '$PROJECT_ID']
images:
- 'gcr.io/${PROJECT_ID}/firebase'
