steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=firebase-development.enc
  - --plaintext-file=.development.env
  - --location=global
  - --keyring=${_KEYRING_NAME}
  - --key=${_KEY_NAME}
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['npm', 'run', 'firebase', 'deploy', '--token', '${_FIREBASE_TOKEN}', '-P', '$PROJECT_ID']