steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
  dir: 'functions/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/firebase', '.' ]
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: ['--token', '${_FIREBASE_TOKEN}', 'deploy', '-P', '$PROJECT_ID', '--only', 'functions']
  dir: 'functions/'
images:
- 'gcr.io/${PROJECT_ID}/firebase'
